### ISSUE TITLE
iOS 11 keyboard suggestion problem

### ISSUE THREAD

**Issue by dariolr** [tkach/PinCodeTextField#10]
in iOS 11 can't type any character from first row of keyboard ( see attachment img )

it work if i hide suggestion list above keyboard in settings.

how hide suggestion list programmatically? 

thank you
![image-1](https://user-images.githubusercontent.com/15995182/28958078-1d281dc8-78f5-11e7-87c0-72fbd0bb9530.jpg)

**Comment by tkach** [comment]
Hi, thanks for opening the issue.
Fixed it, please take the updated version. You may regulate suggestion list enable/disable by setting autocorrectionType property, however now suggestions are disabled by default.

/// Longer answer 
It may be controlled by setting pinCodeTextField.autocorrectionType = .no.
This will disable suggestion list just for the current control.
This property comes from UITextInputTraits protocol and therefore works for any of its descendants (such as UITextField, UIView).
However problem were that I forgot to add some of UITextInputTraits properties (including autocorrectionType) to PinCodeTextField.

**Comment by dariolr** [comment]
Thanks a lot
