### ISSUE TITLE
 UIKeyboardAppearance dark? 

### ISSUE THREAD

**Issue by ADevelopStudio** [tkach/PinCodeTextField#11]
for my app I need all keyboards to be UIKeyboardAppearance.dark
Is there any way to make it?

**Comment by tkach** [comment]
Hi, @ADevelopStudio you can customize UIKeyboardAppearance via keyboardAppearance property.
`public var keyboardAppearance: UIKeyboardAppearance`
You need to set
 `pinCodeTextField.keyboardAppearance = .dark`

**Comment by ADevelopStudio** [comment]
I think I was using the previous version without .keyboardAppearance property.
Thanks!
