### ISSUE TITLE
Add Keyboard Type

### ISSUE THREAD

**Issue by saqibomer** [tkach/PinCodeTextField#15]
Really great repo. I appreciate your work. Can you please keyboard type as well? (Numeric, Email etc)

**Comment by tkach** [comment]
Hello, thanks for your interest in this repo!
Please look at this property, in PinCodeTextField class, it should suite your needs well.
`public var keyboardType: UIKeyboardType = UIKeyboardType.alphabet`
Unfortunately UIKeyboardType is not available in IB for custom views (I can't mark it as IBInspectable), so please set it in your code to your preferred keyboard type.

**Comment by tkach** [comment]
P.s. You can see example of keyboardType setting here
https://github.com/tkach/PinCodeTextField/blob/master/PinCodeTextFieldExample/ViewController.swift
 at line 22.

**Comment by saqibomer** [comment]
Thank you. Yes, I noticed that link. Please close this issue.
