### ISSUE TITLE
Option to add custom inputAccessoryView

### ISSUE THREAD

**Issue by todesengelS** [tkach/PinCodeTextField#17]
`
       let nextButtonItem = UIBarButtonItem(title: NSLocalizedString("NEXT",
                                                                      comment: ""),
                                             style: .done,
                                             target: self,
                                             action: #selector(pinCodeNextAction))

        let toolbar = UIToolbar()
        toolbar.items = [UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil),
                         nextButtonItem]
        toolbar.barStyle = .default
        self.codeTextField.inputAccessoryView = toolbar`

The above code throws error saying **Cannot assign to property: 'inputAccessoryView' is a get-only property**. 

Please resolve this.

.

**Comment by tkach** [comment]
Thanks for reporting the issue. I'll fix this in the nearest days.

**Comment by tkach** [comment]
@todesengelS I've added inputAccessoryView support, please check the new version. You have 2 options for setting inputAccessoryView:
1. I've added sample toolbar as an accessory view to Example project, please look at ViewController.swift (`viewDidLoad` method). One thing I wanted to note — you should call `sizeToFit()` on your UIToolbar instance so it will have correct bounds.
2. I marked inputAccessoryView property with @IBOutlet attribute, so it's possible to set it in .xib or .storyboard file 
![5dbaa364b6](https://user-images.githubusercontent.com/1849482/31684429-702f7d86-b388-11e7-889c-8612dc966610.jpg)
