### ISSUE TITLE
Update for Swift 4.0 

### ISSUE THREAD

**Issue by Momeks** [tkach/PinCodeTextField#19]
Hi , I just install PinCodeTextfield , but xcode shows me these warnings :

>  'characters' is deprecated: Please use String or Substring directly

` let inputTextCount = text?.characters.count ?? 0`

Please update it for swift 4.o

**Comment by tkach** [comment]
Thank you for reporting, I'll fix this in the nearest days

**Comment by tkach** [comment]
Done! Also, pushed it to Cocoapods master repo, so you don't need to specify project's URL in Podfile
