### ISSUE TITLE
How do I check when a UITextField changes?

### ISSUE THREAD

**Issue by Balashov152** [tkach/PinCodeTextField#2]
Hi, thanks for this solution, it really helped me. But, i want see when characters in TextFiled changes. Maybe, there is something on the like 
func textFieldDidChange(textField: UITextField) {
}

**Comment by tkach** [comment]
Hi, thanks for your feedback, seems that it's useful to have this delegate callback.
Added it to text field delegate, please check new version (0.0.3)

**Comment by Balashov152** [comment]
Thanks, it's working.

**Comment by ovargas-aeropost** [comment]
Hi, how did you implement this textFieldDidChange? Im little lost with this. :)

**Comment by tkach** [comment]
@ovargas-aeropost please take a look at the example project, ViewController class, https://github.com/tkach/PinCodeTextField/blob/master/PinCodeTextFieldExample/ViewController.swift
This is what you need:
`func textFieldValueChanged(_ textField: PinCodeTextField)`  method of PinCodeTextFieldDelegate
