### ISSUE TITLE
"Use of undeclared type 'PinCodeTextField"

### ISSUE THREAD

**Issue by mozamonkey** [tkach/PinCodeTextField#20]
The error: Use of undeclared type 'PinCodeTextField' keeps being displayed when calling the delegate

**Comment by tkach** [comment]
Hi, what swift version do you use?

**Comment by mozamonkey** [comment]
Hi, I use Swift 4

**Comment by tkach** [comment]
Ok, thanks for clarification. 
There is already another issue regarding Swift 4 support, so I will definitely fix this in the nearest days.

**Comment by tkach** [comment]
Seems that issue is fixed now. I don't get any errors after migrating project to Swift 4
