### ISSUE TITLE
How to use this cool control in ObjectiveC project?

### ISSUE THREAD

**Issue by hxdev** [tkach/PinCodeTextField#25]
As title! Any instruction here?

**Comment by oleksandr-tkachenko-w** [comment]
I'm really sorry, missed issues here. I had to drop Objective-C compatibility in favor of Swift 3, but you can use previous version, 0.0.7 in Objective-C projects. 
In your podfile:
`pod 'PinCodeTextField', '-> 0.0.7'`

**Comment by tkach** [comment]
I'm really sorry, missed issues here. I had to drop Objective-C compatibility in favor of Swift 3, but you can use previous version, 0.0.7 in Objective-C projects.
In your podfile:
pod 'PinCodeTextField', '-> 0.0.7'

**Comment by tkach** [comment]
I hope my response resolved your issue, so closing it. If you need further assistance please feel free to  open new issue

**Comment by devovipul** [comment]
i can not import it even 
pod 'PinCodeTextField', '~> 0.0.7'
not working in Objective c Project

email : devovipul@gmail.com
skype: devo_vipul
