### ISSUE TITLE
how to clear the text

### ISSUE THREAD

**Issue by quanguyen** [tkach/PinCodeTextField#3]
Hi,

I need to clear the text for user to retry, thus

```
pincode.text = "" // or nil
_ = pincode.becomeFirstResponder()
```

But it does not work. It seems that clear text function is not supported?

Regards

**Comment by tkach** [comment]
Hi @quanguyen thanks for opening the issue. Yes, now it's not supported, let me fix this and I'll reply you asap

**Comment by tkach** [comment]
@quanguyen Please check the new version 0.0.4

**Comment by quanguyen** [comment]
Thanks
