### ISSUE TITLE
Implement to Objective C - Delegate method not shown.

### ISSUE THREAD

**Issue by eshajari** [tkach/PinCodeTextField#30]
It is not showing any delegate methods for Protocol in Objective-C Implementation.

**Comment by tkach** [comment]
I had to drop Objective-C compatibility, but you can use previous version, 0.0.7 in Objective-C projects.
In your podfile:
pod 'PinCodeTextField', '-> 0.0.7'

**Comment by eshajari** [comment]
The above pod install shows error to me.

So Please try 
`pod 'PinCodeTextField', :git => "https://github.com/tkach/PinCodeTextField"`


Issue doesnt get solved althought I check out the 0.0.7.

But the issue was within the swift protocol file.

add` @objc ` before the `public protocol PinCodeTextfieldDelegate`

Now I am able to implement delegate methods.

Thanks!
