### ISSUE TITLE
Swift 4.2 and Xcode 10

### ISSUE THREAD

**Issue by shoaibnomani** [tkach/PinCodeTextField#40]
Can you please update this library for swift 4.2, Xcode 10 and iOS 12?

**Comment by shoaibnomani** [comment]
Is anyone working on it?

**Comment by klemenzagar91** [comment]
Looks like the library is already written in swift 4. For my project, the solution was to click on Pods in the xcode navigation and then select target PinCodeTextField. And open build settings for this target. 

There you can search for Swift Language version and I needed to set it to Swift 4.

If your project is written in swift, the app should now compile just fine. For my case I have a project written in objective c and I got another error after solving the first one. And this second solution I found here https://stackoverflow.com/questions/50096025/it-gives-errors-when-using-swift-static-library-with-objective-c-project/50495316#50495316

**Comment by RomanPodymov** [comment]
Hello @shoaibnomani 
PinCodeTextField 0.2 supports Swift 5, you can close the issue.

**Comment by shoaibnomani** [comment]
> Hello @shoaibnomani
> PinCodeTextField 0.2 supports Swift 5, you can close the issue.

Thanks. Closed.
