### ISSUE TITLE
Support for .oneTimeCode?

### ISSUE THREAD

**Issue by Rdbrennan** [tkach/PinCodeTextField#67]

**Comment by adamhongmy** [comment]
Hi, I was wondering about this too. Did you solve it or let it go?

**Comment by adamhongmy** [comment]
Oh wow, ok. I look forward for your code snippet. :)

**Comment by Rdbrennan** [comment]
Hi Adam!

I'm attaching the project in this email. I added some comments, but it
should be pretty self-explanatory. If you want to check the .oneTimeCode
test, just send run the project on your actual device, not simulator, and
send a text to yourself like so:

"Use 820366 as your login code for this project."


If you have any questions shoot me an email and I'll try to get back to you
as soon as I can!


Best,

Robert
*______________*

*Robert Brennan*Mobile: 662 671 3778
Email: rdbrenna@gmail.com
LinkedIn: http://www.linkedin.com/in/robert-brennan0

**Comment by adamhongmy** [comment]
Hi Rdbrennan, I don’t see any attachment. I think you didn’t realize that we are talking in GitHub issue and not via email.

**Comment by Rdbrennan** [comment]
Ah no I did not know that. My email is rdbrenna@gmail.com. Email me on
there and I'll send it to you.
*______________*

*Robert Brennan*Mobile: 662 671 3778
Email: rdbrenna@gmail.com
LinkedIn: http://www.linkedin.com/in/robert-brennan0
