### ISSUE TITLE
first responder.

### ISSUE THREAD

**Issue by MaeseppTarvo** [tkach/PinCodeTextField#8]
How do you assign first responder to the textField?

**Comment by tkach** [comment]
Hi @MaeseppTarvo 
PinCodeTextField becomes the first responder in the case of user interaction event, for example when user taps it.
Or you may call becomeFirstResponder() on your PinCodeTextField instance just like with other UIResponder subclasses. 
This behavior may be tested with example project, if you add this lines to viewDidLoad() method of ViewController

```
DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) { 
            self.pinCodeTextField.becomeFirstResponder()
        }
```

**Comment by MaeseppTarvo** [comment]
@tkach Hey again. It is not working for some reson. It works with default UITextField but not with this one.
